CONFIG += no_fixpath
QT = core gui widgets
CONFIG += no_fixpath
QT = core gui widgets
CONFIG += no_fixpath
QT = core gui widgets
CONFIG += no_fixpath
QT = core gui widgets
CONFIG += no_fixpath
QT = core opengl gui multimedia widgets openglextensions
CONFIG += no_fixpath
QT = core opengl gui multimedia widgets openglextensions
CONFIG += no_fixpath
QT = core opengl gui multimedia widgets openglextensions
CONFIG += no_fixpath
QT = core opengl gui multimedia widgets openglextensions
CONFIG += no_fixpath
QT = core opengl gui multimedia widgets openglextensions
CONFIG += no_fixpath
QT = core opengl gui multimedia widgets openglextensions
CONFIG += no_fixpath
QT = core opengl gui multimedia widgets openglextensions
CONFIG += no_fixpath
QT = core opengl gui multimedia widgets openglextensions
CONFIG += no_fixpath
QT = core opengl gui multimedia widgets openglextensions
CONFIG += no_fixpath
QT = core opengl gui multimedia widgets openglextensions
CONFIG += no_fixpath
QT = core opengl gui multimedia widgets openglextensions
CONFIG += no_fixpath
QT = core opengl gui multimedia widgets openglextensions
CONFIG += no_fixpath
QT = core opengl gui multimedia widgets openglextensions
